import { NextRequest, NextResponse } from 'next/server';

// OpenAI API configuration
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_BASE_URL = process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';

interface OptimizationRequest {
  prompt: string;
  model?: string;
  maxTokens?: number;
}

interface OptimizationResponse {
  improvedPattern: string;
  explanation: string;
  expectedImprovement: number;
  confidence: number;
}

export async function POST(request: NextRequest) {
  try {
    // Validate API key
    if (!OPENAI_API_KEY) {
      console.error('OpenAI API key not configured');
      return NextResponse.json(
        { error: 'AI optimization service not available' },
        { status: 503 }
      );
    }

    const body: OptimizationRequest = await request.json();
    const { prompt, model = 'gpt-4-turbo-preview', maxTokens = 500 } = body;

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      );
    }

    console.log('Sending regex optimization request to AI:', { prompt: prompt.substring(0, 200) + '...', model });

    // Call OpenAI API
    const response = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: 'system',
            content: 'You are a regex expert specializing in banking transaction patterns. Always respond with valid JSON only. Do not include explanations outside the JSON structure.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: maxTokens,
        temperature: 0.3, // Lower temperature for more consistent regex patterns
        response_format: { type: 'json_object' }, // Force JSON response
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenAI API error:', response.status, errorText);
      return NextResponse.json(
        { error: `AI service error: ${response.statusText}` },
        { status: response.status }
      );
    }

    const result = await response.json();
    console.log('AI response received:', result);

    // Extract the content from the AI response
    const content = result.choices?.[0]?.message?.content;
    if (!content) {
      console.error('No content in AI response');
      return NextResponse.json(
        { error: 'No response from AI service' },
        { status: 500 }
      );
    }

    // Parse the JSON response
    let optimizationResult: OptimizationResponse;
    try {
      optimizationResult = JSON.parse(content);
    } catch (parseError) {
      console.error('Failed to parse AI response as JSON:', content, parseError);
      return NextResponse.json(
        { error: 'Invalid response format from AI service' },
        { status: 500 }
      );
    }

    // Validate the response structure
    const requiredFields = ['improvedPattern', 'explanation', 'expectedImprovement', 'confidence'];
    const missingFields = requiredFields.filter(field => !(field in optimizationResult));

    if (missingFields.length > 0) {
      console.error('Missing required fields in AI response:', missingFields, optimizationResult);
      return NextResponse.json(
        { error: 'Incomplete response from AI service' },
        { status: 500 }
      );
    }

    // Validate the improved pattern
    try {
      new RegExp(optimizationResult.improvedPattern, 'i');
    } catch (regexError) {
      console.error('Invalid regex pattern from AI:', optimizationResult.improvedPattern, regexError);
      return NextResponse.json(
        { error: 'Invalid regex pattern generated by AI' },
        { status: 500 }
      );
    }

    console.log('Regex optimization successful:', optimizationResult);
    return NextResponse.json(optimizationResult);

  } catch (error) {
    console.error('Unexpected error in AI optimization:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// Health check endpoint
export async function GET() {
  return NextResponse.json({
    status: 'healthy',
    service: 'AI Regex Optimization',
    available: !!OPENAI_API_KEY,
    timestamp: new Date().toISOString(),
  });
}